name = "Processing"
grammar = "java"
path_suffixes = ["pde"]
line_comments = ["// "]
tab_size = 2
brackets = [
  { start = "(", end = ")", close = true, newline = false, not_in = ["string", "comment"] },
  { start = "[", end = "]", close = true, newline = false, not_in = ["string", "comment"] },
  { start = "{", end = "}", close = true, newline = true, not_in = ["string", "comment"] },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment"] },
  { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] }
]
